/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"


export default function Model({ ...props }) {
  useFrame((state, delta) => {
    console.log(actions)
    actions.SPIN.play()
  
     });
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./untitled.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, 0, 0]} scale={0.01}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} >
          <group name="82bb1db02f9e4a1289d271600274e503fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="background" position={[0, 0, -40000]} scale={[0.001, 0.001, 0.001]}>
                  <group name="Object_32" position={[0, 0, 0]}>
                    <mesh name="background_Material_#26_0" geometry={nodes['background_Material_#26_0'].geometry} material={materials.Material_26} />
                  </group>
                </group>
                <group name="Group001" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="TextPlus001" position={[0, 0, 0]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_29" position={[0, 0, -40000]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus001_Material_#25_0" geometry={nodes['TextPlus001_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus002" position={[0, 0, 0]} rotation={[0, -Math.PI / 4, 0]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_8" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus002_Material_#25_0" geometry={nodes['TextPlus002_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus003" position={[0, 0, 0]} rotation={[0, -1.57, 0]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_11" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus003_Material_#25_0" geometry={nodes['TextPlus003_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus004" position={[0, 0, 0]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_14" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus004_Material_#25_0" geometry={nodes['TextPlus004_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus005" position={[0, 0, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_17" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus005_Material_#25_0" geometry={nodes['TextPlus005_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus006" position={[0, 0, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_26" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus006_Material_#25_0" geometry={nodes['TextPlus006_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus007" position={[0, 0, 0]} rotation={[0, 1.57, 0]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_23" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus007_Material_#25_0" geometry={nodes['TextPlus007_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                  <group name="TextPlus008" position={[0, 0, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.02, 0.02, 0.02]}>
                    <group name="Object_20" position={[-0.06, 12.73, -4.77]} rotation={[Math.PI / 2, 0, 0]}>
                      <mesh name="TextPlus008_Material_#25_0" geometry={nodes['TextPlus008_Material_#25_0'].geometry} material={materials.Material_25} />
                    </group>
                  </group>
                </group>
                <group name="Sphere001" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
                  <mesh name="Sphere001_01_-_Default_0" geometry={nodes['Sphere001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.25, -32.36, -0.04]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./untitled.gltf')
