/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/DPM-CT.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[0.01, -0.22, 0.35]} rotation={[Math.PI / 2, 0, 0]} scale={1.06}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh geometry={nodes.EyeLeft001.geometry} material={nodes.EyeLeft001.material} skeleton={nodes.EyeLeft001.skeleton} />
          <skinnedMesh geometry={nodes.EyeRight001.geometry} material={nodes.EyeRight001.material} skeleton={nodes.EyeRight001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Beard001.geometry} material={materials.Wolf3D_Beard} skeleton={nodes.Wolf3D_Beard001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Head001.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
          <skinnedMesh geometry={nodes.Wolf3D_Teeth001.geometry} material={nodes.Wolf3D_Teeth001.material} skeleton={nodes.Wolf3D_Teeth001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/DPM-CT.glb')
